---
- name: Kubernetes Deployment
  hosts: all
    # become: true
  tasks:
  - name: create new namespace
    command: kubectl apply -f /home/ubuntu/todoApp/namespace.yaml
  - name: create new deployment
    command: kubectl apply -f /home/ubuntu/todoApp/deployment.yml
  - name: create new service
    command: kubectl apply -f /home/ubuntu/todoApp/service.yaml 
