apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-project1-app
  labels:
    app: k8s-project1
  namespace: app 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-project1
  template:
    metadata:
      labels:
        app: k8s-project1
    spec:
      containers:
      - name: k8s-project1-ctr
        image: abhishekg14/k8s-project1:latest
        ports:
        - containerPort: 8000