apiVersion: v1
kind: Service
metadata:
  name: k8s-project1-service
  namespace: app

spec:
  selector:
    app: k8s-project1
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
  type: NodePort
